#
# Copyright (c) 2020-2020 Huawei Technologies Co., Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

#obj-y += mt6765/
obj-y += mt6853/
#obj-y += mt6833/
#obj-y += mt6877/
obj-y += mt6885/
#obj-y += mt6893/

